# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0

  resources:
    # --- Repo klonen (robust, fällt auf C:\ zurück, wenn Z:\ noch nicht da ist; läuft nur, wenn Git vorhanden ist) ---
    - resource: PSDscResources/Script
      id: cloneRepo
      settings:
        TestScript: |
          # Bereits geklont?
          if (Test-Path "Z:\workspaces\eshop\.git" -or Test-Path "C:\workspaces\eshop\.git") { return $true }
          return $false
        SetScript: |
          $repoRoot = (Test-Path 'Z:') ? 'Z:\workspaces' : 'C:\workspaces'
          if (-not (Get-Command git.exe -ErrorAction SilentlyContinue)) {
            Write-Host "Git nicht gefunden; überspringe Clone in diesem Lauf."
            return
          }
          if (-not (Test-Path $repoRoot)) { New-Item -ItemType Directory -Path $repoRoot -Force | Out-Null }
          $target = Join-Path $repoRoot 'eshop'
          if (-not (Test-Path $target)) { New-Item -ItemType Directory -Path $target -Force | Out-Null }
          if (-not (Test-Path (Join-Path $target '.git'))) {
            git clone --quiet https://github.com/contoso-co/eshop.git $target
          }
        GetScript: return $false

    # --- Tools & Apps über WinGet ---
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: docker
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: chrome
      directives:
        description: Install Google Chrome
      settings:
        id: Google.Chrome

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: adobereader
      directives:
        description: Install Adobe Acrobat Reader
      settings:
        id: Adobe.Acrobat.Reader.64-bit

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscode
      directives:
        description: Install Visual Studio Code
      settings:
        id: Microsoft.VisualStudioCode

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: notepadpp
      directives:
        description: Install Notepad++
      settings:
        id: Notepad++.Notepad++

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: azurecli
      directives:
        description: Install Azure CLI
      settings:
        id: Microsoft.AzureCLI

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: terraform
      directives:
        description: Install Terraform
      settings:
        id: Hashicorp.Terraform

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: datagrip
      directives:
        description: Install JetBrains DataGrip
      settings:
        id: JetBrains.DataGrip

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dbeaver
      directives:
        description: Install DBeaver
      settings:
        id: DBeaver.DBeaver.Community

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: storageexplorer
      directives:
        description: Install Azure Storage Explorer
      settings:
        id: Microsoft.Azure.StorageExplorer

    # --- Python 3.12: maschinenweit + PATH (fix für InstallerError 3) ---
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: python
      directives:
        description: Install Python 3.12 (machine-wide)
      settings:
        id: Python.Python.3.12
        scope: machine
        override: |
          InstallAllUsers=1 PrependPath=1 Include_test=0 Include_launcher=1

    # --- WSL aktivieren (keine Distro) ---
    - resource: PSDscResources/Script
      id: enableWsl
      directives:
        description: Aktiviert WSL, falls noch nicht vorhanden
      settings:
        TestScript: |
          try { wsl -l -q > $null 2>&1; return $true } catch { return $false }
        SetScript: |
          wsl --install --no-distribution
        GetScript: return $false
