# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  ########################################
  ### RESOURCES: System Configuration
  ########################################
  resources:
    # Creates a new Dev Drive
    ### -------------------------------------
    - resource: Disk
      id: DevDrive1
      directives:
        module: StorageDsc
        allowPrerelease: true
      settings:
        DiskId: '0'
        DiskIdType: 'Number'
        DriveLetter: 'Z'
        FSLabel: 'Dev Drive 1'
        DevDrive: true
        AllowDestructive: true
        FSFormat: 'ReFS'
        Size: '50GB'
    ### Install Git
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: git
      directives:
        allowPrerelease: true
      settings:
        id: Microsoft.Git
    ### Configure Git to use Default WAM account
    ### -------------------------------------
    - resource: PSDscResources/Script
      dependsOn:
        - git
      directives:
        description: Configure Git to use Default WAM account
      settings:
        SetScript: |
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          [Environment]::SetEnvironmentVariable('GCM_MSAUTH_USEDEFAULTACCOUNT','true','Machine')
          git config --global credential.msauthUseDefaultAccount true
        GetScript: return $false
        TestScript: return $false

    ### Configure GCM for self-hosted GitLab OAuth
    - resource: PSDscResources/Script
      id: gitlabOauthConfig
      dependsOn:
        - git
      directives:
        description: Konfiguriert GCM für selbst-gehostetes GitLab (OAuth)
      settings:
        SetScript: |
          $domain   = "gitlab.bankfrick.li"
          $clientId = "e60e535167320bdced2f21e75f9330bf30de8a7c8b10b1c9be0f49ca23902b7f"
          git config --global credential.https://$domain.oauthClientId "$clientId"
          git config --global credential.https://$domain.oauthScopes "read_repository write_repository"
          git config --global credential.https://$domain.oauthAuthURL  /oauth/authorize
          git config --global credential.https://$domain.oauthTokenURL /oauth/token
        TestScript: |
          $domain   = "gitlab.bankfrick.li"
          $clientId = "e60e535167320bdced2f21e75f9330bf30de8a7c8b10b1c9be0f49ca23902b7f"
          $id = git config --global --get credential.https://$domain.oauthClientId
          return ($id -eq "e60e535167320bdced2f21e75f9330bf30de8a7c8b10b1c9be0f49ca23902b7f")
        GetScript: return $false
    ### Set Swiss German locale and keyboard
    - resource: PSDscResources/Script
      id: setLocaleCH
      directives:
        description: Stellt Schweizerdeutsch (de-CH) als Standard-Sprache, -Tastatur und -Region ein
      settings:
        TestScript: |
          return ((Get-Culture).Name -eq "de-CH")
        SetScript: |
          $lang = "de-CH"
          Set-WinSystemLocale -SystemLocale $lang
          Set-Culture $lang
          Set-WinHomeLocation -GeoId 223   # Schweiz
          $list = New-WinUserLanguageList $lang
          # explizit Swiss-German Keyboard 0807
          $list[0].InputMethodTips.Clear()
          $list[0].InputMethodTips.Add("0807:00000807")
          Set-WinUserLanguageList $list -Force
        GetScript: return $false